project:
  type: website
  output-dir: docs

website:
  title: "Portfolio - Henry"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/HenryG02
      - icon: linkedin
        href: https://linkedin.com/in/henry-goya

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



